### ISSUE TITLE
Stop prefixing interfaces with 'I'

### ISSUE THREAD

**Issue by tomasvosylius** [Stuyk/altv-athena#1]
As this may seem like a personal preference, the TypeScript handbook does not suggest prefixing interfaces with 'I'. 
This convention is borrowed from the past and I believe this project shouldn't use it since:

- it is against encapsulation principles.
- Hungarian notation times are long gone.
- it is a bad naming convention.
- major TypeScript based frameworks and libraries discourage from this ([Angular](https://angular.io/guide/styleguide#style-03-03), lib.d.ts etc)

A more detailed discussion and reasons can be found [here](https://github.com/microsoft/TypeScript-Handbook/issues/121#issuecomment-412810455) and [here](https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript/41967120#41967120)

**Comment by Stuyk** [comment]
> As this may seem like a personal preference, the TypeScript handbook does not suggest prefixing interfaces with 'I'.
> This convention is borrowed from the past and I believe this project shouldn't use it since:
> 
> * it is against encapsulation principles.
> * Hungarian notation times are long gone.
> * it is a bad naming convention.
> * major TypeScript based frameworks and libraries discourage from this ([Angular](https://angular.io/guide/styleguide#style-03-03), lib.d.ts etc)
> 
> A more detailed discussion and reasons can be found [here](https://github.com/microsoft/TypeScript-Handbook/issues/121#issuecomment-412810455) and [here](https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript/41967120#41967120)

Since this seems to be 'best practice' I'll revert everything to non-i interfaces when I get the time.

I think it's fine but if that's what the standard is then I guess I'll have to adapt.
