### ISSUE TITLE
Consider using TypeScript path mapping for imports

### ISSUE THREAD

**Issue by fmeyertoens** [Stuyk/altv-athena#17]
First, thank you for the awesome project.
Many of the import statements throughout the project are relative imports like here:
https://github.com/Stuyk/altv-athena/blob/042a0d5f9a3758479ba62854aae376053a802e91/src/core/server/athena/main.ts#L1
These imports therefore have to be changed when you move the file which might be inconvenient. TypeScript provides a solution to that problem with path mapping ([Docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping)) which is also set up in Vue projects with TypeScript ([Link](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/generator/template/tsconfig.json#L37)) and Vue itself `([Link](https://github.com/vuejs/vue-next/blob/master/tsconfig.json#L20)).

With the following lines in tsconfig.json
```json
"baseUrl": ".",
"paths": {
    "@src/*": ["src/*"]
},
```
the import from above could look like this:
```typescript
import { SHARED_CONFIG } from '@src/core/shared/configurations/shared'; 
```

Did you consider this option for the project? It can also be incrementally adopted if you want to try it out.

**Comment by Stuyk** [comment]
Leonard wrote about it. Just haven't pursued it yet or tested if it works without issue.

**Comment by LeonardSSH** [comment]
It's a little tricky, you have to do some tests and understand the principle on which these custom paths work. 😊

**Comment by FDiskas** [comment]
Actualy there is posibility that will happen a colition with an real npm module with such name for example `@src/components` - its a legit name for module.
I suggest you just use apsolute imports.
Remove 
```
"paths": {
    "@src/*": ["src/*"]
}
```
and add
```
"inlude": ["src"]
```
and then you can import like so
```
import { SHARED_CONFIG } from '/src/shared/configurations/shared'; 
```
