### ISSUE TITLE
Update playerFuncs.emit.meta

### ISSUE THREAD

**Issue by Stuyk** [Stuyk/altv-athena#292]
Currently it uses an internal custom solution with alt.emitClient. This is no longer necessary and we can use player.setLocalMeta.

Requires refactoring in multiple parts of the code base.

**Comment by prasoonmhwr** [comment]
please assign it to me :)

**Comment by prasoonmhwr** [comment]
@Stuyk just to clarify I just need to replace "alt.emitClient" with this "player.setLocalMeta" at project level?

**Comment by Stuyk** [comment]
@prasoonmhwr Yea also means replacing the internal event listeners I wrote that forward a meta change.
