### ISSUE TITLE
/getitem - Also get items by `dbName`

### ISSUE THREAD

**Issue by Stuyk** [Stuyk/altv-athena#296]
Currently the `/getitem` command only gets items based on their actual name.

Needs to support fetching items by `dbName` which can be done with this function:

https://github.com/Stuyk/altv-athena/blob/6ec8149d36bc0c611b2c18346819af7be1ab820e/src/core/server/systems/item.ts#L87

* Make the `/getitem` check through `ItemFactory.get` first.
* If the result is undefined or null
* Try fetching by name
* if still undefined or null; tell the player it was not found

**Comment by ItsSpencer** [comment]
because I am somehow motivated... i can do it

**Comment by Booster1212** [comment]
Should support quantity param as well instead of default 1
