### ISSUE TITLE
Move Away from Classes with Static Function Calls

### ISSUE THREAD

**Issue by Stuyk** [Stuyk/altv-athena#299]
Anything that uses classes, should use consts instead.

**Old Code**
```ts
export class Something {
    static init() {
        console.log('hello world');
    }
}

Something.init();
```

**New Code**
```ts
const Something2 = {
    init() {
        console.log('hello world');
    }
}

Something2.init();

export Something2;
```

## Why?

Because of how many things use the class version above; we can create incremental performance increases by migrating to just using consts entirely.

![](https://i.imgur.com/zMBFxWn.png)

## Making the Commit

If you decide to make a PR for these refactor changes. Please make sure to tag your commit with #299

**Comment by Lofty-Brambles** [comment]
Is this issue still open? I'd like to work on it @Stuyk

**Comment by Stuyk** [comment]
@Lofty-Brambles Yea there's plenty available for this.

**Comment by Booster1212** [comment]
## Old
```ts
export class Something {
    static init() {
        console.log('hello world');
    }
}

Something.init();
```

## New

```ts
const SomethingConst {
     init() {
        console.log('hello world');
    },
}

export const Something = {
    ...SomethingConst
}```

Better example, the example in the issue above wont work.
