### ISSUE TITLE
Add Temporary Markers

### ISSUE THREAD

**Issue by Booster1212** [Stuyk/altv-athena#319]
I think it would be nice to have a "duration-option for the MarkerController which will remove the Marker after the specified duration.

Which can be usefull for i.e. Temporary Editors, and something else.

**Comment by Stuyk** [comment]
Would require some form of event loop to check when the marker expires. Unless it's fully client-side in which case we should make a separate marker controller for purely client-side single use markers that are meant to be removed often.
