### ISSUE TITLE
Explore Plugin Folder Move

### ISSUE THREAD

**Issue by Stuyk** [Stuyk/altv-athena#324]
Athena currently requires all plugins to be placed inside of `src/core/plugins`.

It would make more sense to create a new folder just called `plugins` and that's where all plugins go.

**What would this require and change?**

* Pathing helpers in tsconfig for `@server` or `@client` or `@shared`
* Moving all plugins to individual repositories and keeping them out of the core framework.
* * This would be an effort to `slim` Athena down to what is actually core; and remove anything extra.
* This would require users to download additional plugins when they get Athena.
* * Allows for more customization, and they are not forced to use core plugins outright.
* Lots of unknowns from a file resolve perspective.

**Why?**

* This removes unnecessary plugins that come with Athena.
* Instead it focuses on just a few core plugins needed for starting the server.
* Allows for other game modes to be quickly built out from a  `slim` Athena.

**Comment by Stuyk** [comment]
Realistically this can be done in steps; and not all at once. Which would be adding the path aliases first. Moving all plugins to use path aliases and so on and so forth.

**Comment by gotgameio** [comment]
Hi, nice idea that would slim framework it self, one thing i would change is aliases which can be @athena/core, @athena/server, @athena/plugins as they are more explicit.

**Comment by Stuyk** [comment]
@gotgameio Only catch with this is that the aliases require a custom build process inside of the SWC script so I don't know how it affects your esbuild thing. I've already got a 'test' branch that made the aliases work but it would definitely force us to use one build process in general.

**Comment by gotgameio** [comment]
The path aliasing itself is not a problem, i already use it with esbuild/webpack in my project. I argue about @athena/ prefix because personally i use it as a library and i include athena/startup in my main resource with path alias @athena/core/server, @athena/core/client, i dont use @server/@client etc prefixes so i think as they will be used only in athena itself my build will not break, i will test 3.9.0-path-aliasing branch to check if it will break anything.

**Comment by Stuyk** [comment]
@gotgameio Okay; lemme know. Also get in Discord if you are not already in Discord.

**Comment by Stuyk** [comment]
I'm not sure if the plugin folder will be moved because of the build issues it will likely introduce. I'm still considering it but I'm not sure at this time. If anything in `4.0.0` we get the path aliasing which makes it a bit cleaner.
