### ISSUE TITLE
Game crashes when trying to enter a car 

### ISSUE THREAD

**Issue by R3DIANCE** [Stuyk/altv-athena#353]
Game crashes when trying to enter a car and there's some more vehicles around.
tested with 13 vehicles around me at the garage.
on latest 3.9.0 branch.
![GTA5_7DdUSy9MKA](https://user-images.githubusercontent.com/13523121/194373326-f0346683-4e0d-4cf6-a314-8e53bb93831c.jpg)

**Comment by R3DIANCE** [comment]
@Stuyk i tested with no moded cars around its seems to works fine,
as soon i spawned a moded car, any moded car and trying to enter a non moded car game crashes.
doesn't matter if the car is moded or not.

**Comment by R3DIANCE** [comment]
seems to work just fine in clean non athena framework.
![GTA5_7U8sRLWNnH](https://user-images.githubusercontent.com/13523121/194553325-a6116342-6f42-4d8a-a3f8-499d2397a343.jpg)

**Comment by Stuyk** [comment]
Unable to reproduce

**Comment by Progefix** [comment]
I had that problem a while ago. You sould check youre resource.cfg there was my problem ^.^

**Comment by R3DIANCE** [comment]
@Progefix do you remember what do in need to change?

**Comment by Progefix** [comment]
Idk just check youre stream.cfg and resource.cfg. if an linked meta is missed or wrong linked it will crash the client
