### ISSUE TITLE
Respawn broken.

### ISSUE THREAD

**Issue by Fanatic191** [Stuyk/altv-athena#381]
At this moment, i found a solution for that, but it can not be last forever. 

Try this until Stuyk found other options for that.

src/core/plugins/core-death/client/index.ts

Make it comment for this line:

          
        /*if (!alt.Player.local.isDead) {   <---THIS
                return;
            }

            if (isAnyMenuOpen(false)) {
                return;
            }*/     <--- to here! CAUTION! Until this line

       Only this IF part. 

    
    For the, atm it is working.

**Comment by jonesXYZ** [comment]
Can you please provied more Informations?
What exactly is broken?
Which Athena Version?
...

**Comment by Fanatic191** [comment]
> Can you please provied more Informations? What exactly is broken? Which Athena Version? ...

If you press the respawn key, the system wont respawn you, only with 'revive' can help. 
 Version the latest. (4.0.2?)
Sry this is my first report, i don't know exactly what do i have to do.

**Comment by BinaryChop** [comment]
Press E to respawn does not work. Broken since 3.9.0. #334

**Comment by jonesXYZ** [comment]
> > Can you please provied more Informations? What exactly is broken? Which Athena Version? ...
> 
> If you press the respawn key, the system wont respawn you, only with 'revive' can help. Version the latest. (4.0.2?) Sry this is my first report, i don't know exactly what do i have to do.

All good, for the next Time provied as much Information as you can.
Then its easier to understand your Issue

**Comment by Fanatic191** [comment]
Just a comment. After i respawn to the nearest hospital, every time freefalling, then spawn in front of nearest hospital. I changes the spots a little bit, atm it is okay. This can be fixed in v5? Thank you Stuyk!

**Comment by Stuyk** [comment]
@Fanatic191 Default respawn behavior is changed in v5. The plugin will be irrelevant for v5; and will have a default system that will automatically spawn a player at the nearest hospital after 5 seconds.

This can be disabled through `Athena.systems.default.death.disable()`. However, once this default behavior is disabled nothing will allow a player to respawn and a new plugin can override the existing functionality entirely.

A lot of the plugins that currently exist will be non-functioning after v5 is released.
