### ISSUE TITLE
Can you explain in detail how to build it

### ISSUE THREAD

**Issue by Ryan-EUAN** [Stuyk/altv-athena#383]
Hello author, could you please explain how to build it in detail? I'd like to study it. Thank you

**Comment by Booster1212** [comment]
I suggest you start by checking out the Athenaframework Docs and the Discord Server. You'll might get an better idea of it works, if you have any specific questions feel free to answer.

To get started checkout this link => https://athenaframework.com/

Also we've a Discord Server which can be found here. => https://discord.gg/TnR25QNP

**Comment by Ryan-EUAN** [comment]
I have read this document, but I still do not know how to build the Athena frame
