### ISSUE TITLE
Cannot access 'enabled' Error

### ISSUE THREAD

**Issue by Statuefisch9194** [Stuyk/altv-athena#405]
Just wanted to try out Athena again and got this Error i tried multiple things but nothing worked.

(Yes i tried npm fix)

![grafik](https://user-images.githubusercontent.com/104876759/229426693-f65197bb-fc17-44f9-a085-f1f9d2e9e96b.png)

**Comment by KonstantinKG** [comment]
Maybe Athena's developers will fix it in the future. But what helped for me, to in "C:\AltV\Athena\altv-athena\src\core\server\systems\defaults\time.ts" change 'let' to 'var'.
Make sure to change it for all variables (enabled, interval, minute and hour).
After that everything worked.

**Comment by Statuefisch9194** [comment]
Now it works fine. Tanks for your Help!
