### ISSUE TITLE
Vite can't resolve the altv-shared module

### ISSUE THREAD

**Issue by CodeLit** [Stuyk/altv-athena#440]
Reproduces on: v5.1.0, 6.0.0

<img width="906" alt="image" src="https://github.com/Stuyk/altv-athena/assets/37398131/acd028f3-c4df-4275-b987-97facc1e851b">

**Comment by Stuyk** [comment]
What is your node version?

I can't reproduce this on Node V20+

**Comment by CodeLit** [comment]
Sorry, it looks like my fault, there are some old files from old versions of athena that are causing the error. It looks like I'll have to connect the athena folder as a git sub-module to be able to upgrade to a newer version. Then somehow add the necessary files from the main repository from above. Ideally wrap it all in docker and make a cross-platform solution. Thanks, I'll keep thinking about how to do it all.

**Comment by CodeLit** [comment]
Sorry, it looks like my fault, there are some old files from old versions of athena that are causing the error. It looks like I'll have to connect the athena folder as a git sub-module to be able to upgrade to a newer version. Then somehow add the necessary files from the main repository from above. Ideally wrap it all in docker and make a cross-platform solution. Thanks, I'll keep thinking about how to do it all.
