### ISSUE TITLE
Failed to load resource core

### ISSUE THREAD

**Issue by Jensenccc** [Stuyk/altv-athena#442]
![C__WINDOWS_system32_cmd exe  2023_10_6 1_44_58](https://github.com/Stuyk/altv-athena/assets/107613222/5594e4be-b67f-45fa-86ba-a693a3f2b0f2)

**Comment by Stuyk** [comment]
Make sure you have `git` installed.
Make sure you have `Node 18+` installed.
Make sure you run `npm install`
Make sure you run `npm run update`

**If you are on windows:**
Make sure you run `npm run windows`

**If you are on Linux:**
Make sure you run `npm run linux`

**DO NOT RUN THE EXECUTABLE FOR `altv-server` DIRECTLY**

**Comment by Jensenccc** [comment]
![alt_V Multiplayer 2023_10_6 2_11_01](https://github.com/Stuyk/altv-athena/assets/107613222/b678df70-bf4b-4e45-8af7-32507135fb20)

**Comment by Stuyk** [comment]
Please get in Discord if you need further support. It's harder to diagnose through comments like this.
