### ISSUE TITLE
Every opensource plugin is not working from now on. Api importing error.

### ISSUE THREAD

**Issue by CodeLit** [Stuyk/altv-athena#452]
Now after the update, plugins stopped working, because the import principle has changed. It is necessary to return backward compatibility for plugins to work.

![image](https://github.com/Stuyk/altv-athena/assets/37398131/42d78ccc-ec8e-496a-a8a5-a5ea8e96acdc)

For example, this code is from [documentation](https://athenaframework.com/tutorials/free/making-plugins/creating-plugins#quick-plugin-template):

```ts
import * as alt from 'alt-server';
import * as Athena from '@AthenaServer/api';

const PLUGIN_NAME = 'myPlugin';
Athena.systems.plugins.registerPlugin(PLUGIN_NAME, () => {
    alt.log('Hello from Athena Server!');
});
```

is not working, because we need to add index file in the end:

```ts
import * as alt from 'alt-server';
import * as Athena from '@AthenaServer/api/index.js';

const PLUGIN_NAME = 'myPlugin';
Athena.systems.plugins.registerPlugin(PLUGIN_NAME, () => {
    alt.log('Hello from Athena Server!');
});
```

Now code is works, and there is no error anymore.

**Comment by Stuyk** [comment]
This is normal behavior. See this post from the alt:V team back in February of 2023.

https://discord.com/channels/371265202378899476/585862696281571341/1079021033199243274

**Comment by CodeLit** [comment]
I'm closing the issue, but I still think there should be backwards compatibility.
