### ISSUE TITLE
No function for returning { slot: number; tab: number } for an item

### ISSUE THREAD

**Issue by FrankoFM** [Stuyk/altv-athena#55]
[`playerFuncs.inventory.isInInventory`](https://github.com/Stuyk/altv-athena/blob/f18fd2c06118f6820340c15b9664bbf5682bf7d1/src/core/server/extensions/playerFunctions/inventory.ts#L213) is currently returning `{ index: number; tab: number }` and not `{ slot: number; tab: number }`
So you can't get the Item with [`playerFuncs.inventory.getInventoryItem` ](https://github.com/Stuyk/altv-athena/blob/f18fd2c06118f6820340c15b9664bbf5682bf7d1/src/core/server/extensions/playerFunctions/inventory.ts#L131) like in the example below.
[`playerFuncs.inventory.isInInventory`](https://github.com/Stuyk/altv-athena/blob/f18fd2c06118f6820340c15b9664bbf5682bf7d1/src/core/server/extensions/playerFunctions/inventory.ts#L213) can't be changed because it's index value is used in other functions.
I guess we need a new function where it returns the slot. Like this:

```
function isInInventory(p: alt.Player, item: Partial<Item>): { tab: number; slot: number } | null {
    for (let t = 0; t < p.data.inventory.length; t++) {
        const tab = p.data.inventory[t];

        if (tab.length <= 0) {
            continue;
        }

        for (let i = 0; i < tab.length; i++) {
            const inventoryItem = tab[i];
            if (!item) {
                continue;
            }

            const objectKeys = Object.keys(item);
            const keyIndex = objectKeys.findIndex((key) => item[key] === inventoryItem[key]);

            if (keyIndex <= -1) {
                continue;
            }

            return { tab: t, slot: inventoryItem.slot };
        }
    }

    return null;
}
```

I don't know if this is intended or not thats why I didn't make a Pull Request. And I don't know how I should name the function.

The Example I referred to found at [Docs](https://athena.stuyk.com/basic-scripting/adding-items)
```
const slotInfo: { slot: number; tab: number } | null = playerFuncs.inventory.isInInventory({ name: 'Micro SMG' });
if (!slotInfo) {
    playerFuncs.emit.message(player, `Item was not found!`);
    return;
}

const item: Item = playerFuncs.inventory.getInventoryItem(player, slotInfo.slot, slotInfo.tab);
if (!item) {
    playerFuncs.emit.message(player, `Item was not found!`);
    return;
}
```

**Comment by Stuyk** [comment]
Can be done in this way:

```ts
const someItemInfo = playerFuncs.inventory.isInInventory(player, { name: 'Burger' });
const item = player.data.inventory[someItemInfo.tab][someItemInfo.index];
```
